version: '3'

services:
  nodejs-db:
    container_name: nodejs-db
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    networks:
      - base_network
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  nodejs-api:
    container_name: nodejs-api
    image: node:lts
    networks:
      - base_network
    ports:
      - ${PORT}:${PORT}
    command: sh -c "npm run start:dev"
    depends_on:
      - nodejs-db
    working_dir: /app
    volumes:
      - .:/app
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@nodejs-db:5432/${POSTGRES_DB}?schema=public

networks:
  base_network:


volumes:
  db-data:
